version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: bingo-postgres
    environment:
      POSTGRES_USER: bingo_user
      POSTGRES_PASSWORD: bingo_password
      POSTGRES_DB: bingo_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U bingo_user -d bingo_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
